version: '3.7'

networks:
  inception_net:
    name: inception_net
    driver: bridge


services:
  nginx:
    image: nginx
    ports:
      - 443:443
    restart:
      always
    build: setup/nginx/
    networks:
      - inception_net
    container_name: nginx

